name: Node.js CI

"on":
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
      - name: corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn --immutable
      - name: Formatter
        run: yarn format:ci
      - name: Lint
        run: yarn lint
      - name: Build Packages
        run: BASE_PATH=/react-icons ./build-script.sh
      - uses: actions/upload-artifact@v4
        with:
          path: packages/_react-icons_*/*.tgz
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/preview-astro/dist
        if: github.ref == 'refs/heads/master'
      - name: generate notes
        run: gh api /repos/react-icons/react-icons/releases/generate-notes -f tag_name=${GITHUB_REF#tags/} --jq .body >> RELEASE_NOTES
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.ref, 'tags/')
      - name: append versions
        run: |
          echo >> RELEASE_NOTES
          cat packages/react-icons/VERSIONS >> RELEASE_NOTES
        if: contains(github.ref, 'tags/')
      - name: cat
        run: cat RELEASE_NOTES
        if: contains(github.ref, 'tags/')
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/_react-icons_*/*.tgz"
          bodyFile: "RELEASE_NOTES"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'snapshot') }}
        if: contains(github.ref, 'tags/')
